/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfessionalDashboardRouteImport } from './routes/professional-dashboard'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerDashboardRouteImport } from './routes/customer-dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AddServiceRouteImport } from './routes/add-service'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalProviderIdRouteImport } from './routes/professional.$providerId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalDashboardRoute = ProfessionalDashboardRouteImport.update({
  id: '/professional-dashboard',
  path: '/professional-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer-dashboard',
  path: '/customer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddServiceRoute = AddServiceRouteImport.update({
  id: '/add-service',
  path: '/add-service',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalProviderIdRoute = ProfessionalProviderIdRouteImport.update({
  id: '/professional/$providerId',
  path: '/professional/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-service': typeof AddServiceRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/professional-dashboard': typeof ProfessionalDashboardRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/professional/$providerId': typeof ProfessionalProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-service': typeof AddServiceRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/professional-dashboard': typeof ProfessionalDashboardRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/professional/$providerId': typeof ProfessionalProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-service': typeof AddServiceRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/professional-dashboard': typeof ProfessionalDashboardRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/professional/$providerId': typeof ProfessionalProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-service'
    | '/admin-dashboard'
    | '/customer-dashboard'
    | '/login'
    | '/messages'
    | '/professional-dashboard'
    | '/register'
    | '/services'
    | '/professional/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-service'
    | '/admin-dashboard'
    | '/customer-dashboard'
    | '/login'
    | '/messages'
    | '/professional-dashboard'
    | '/register'
    | '/services'
    | '/professional/$providerId'
  id:
    | '__root__'
    | '/'
    | '/add-service'
    | '/admin-dashboard'
    | '/customer-dashboard'
    | '/login'
    | '/messages'
    | '/professional-dashboard'
    | '/register'
    | '/services'
    | '/professional/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddServiceRoute: typeof AddServiceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ProfessionalDashboardRoute: typeof ProfessionalDashboardRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  ProfessionalProviderIdRoute: typeof ProfessionalProviderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-dashboard': {
      id: '/professional-dashboard'
      path: '/professional-dashboard'
      fullPath: '/professional-dashboard'
      preLoaderRoute: typeof ProfessionalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-dashboard': {
      id: '/customer-dashboard'
      path: '/customer-dashboard'
      fullPath: '/customer-dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-service': {
      id: '/add-service'
      path: '/add-service'
      fullPath: '/add-service'
      preLoaderRoute: typeof AddServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/$providerId': {
      id: '/professional/$providerId'
      path: '/professional/$providerId'
      fullPath: '/professional/$providerId'
      preLoaderRoute: typeof ProfessionalProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddServiceRoute: AddServiceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ProfessionalDashboardRoute: ProfessionalDashboardRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  ProfessionalProviderIdRoute: ProfessionalProviderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
